Add loader to sidepage search (without MainPage)
ekaterinburgdev/guides pull request #68
Opened 2023-02-08 19:26 UTC by AtkishkinVlad

Add loader in guides

2023-02-09 10:53 UTC, fidlow requested changes

2023-02-09 10:53 UTC, fidlow commented on components/Toolbar/MainPageToolbar.jsx
> +                setIsLoading(false)
where is declaration of this function?

2023-02-09 10:53 UTC, fidlow commented on components/Toolbar/MainPageToolbar.jsx
> +            loadingState.set(true)
where is import statement?

2023-02-09 10:53 UTC, fidlow commented on components/Toolbar/MainPageToolbar.jsx
> +            loadingState.set(false)
where is import statement?

2023-02-09 10:53 UTC, fidlow commented on components/SidePage/Suggestions/Suggestions.jsx
> +            ) : null}
```suggestion
            {guideSuggestions.length > 0 && (
                guides?.map((guideSuggest) => <GuideSuggestion guideSuggestion={guideSuggest} />}
            {guideSuggestions.length === 0 && currentQuery.length > 0 && (
                <p className={styles.Suggestions__not_found}>Ничего не нашли</p>
            )}
```

2023-02-09 10:54 UTC, fidlow commented on components/SidePage/Suggestions/Suggestions.jsx
> +            ) : null}
It's easier to read

2023-02-12 06:53 UTC, AtkishkinVlad commented on components/Toolbar/MainPageToolbar.jsx
> +            loadingState.set(true)
Fix

2023-02-12 06:53 UTC, AtkishkinVlad commented on components/Toolbar/MainPageToolbar.jsx
> +                setIsLoading(false)
Fix

2023-02-12 06:53 UTC, AtkishkinVlad commented on components/Toolbar/MainPageToolbar.jsx
> +            loadingState.set(false)
Fix

2023-02-12 06:53 UTC, AtkishkinVlad commented on components/SidePage/Suggestions/Suggestions.jsx
> +            ) : null}
Fix

2023-02-13 08:04 UTC, fidlow submitted a review, later dismissed

2023-03-13 19:19 UTC, a-chabin commented
Let's add styles to loader container
```
max-width: 60%;
aspect-ratio: 1 / 1;
width: 400px;
```

This should fix:
- Too big loader 
- Horizontal scroll

https://user-images.githubusercontent.com/22644149/224806542-8c4f3da9-4f3b-461a-bd12-6ce5c5781cbf.mov

2023-03-13 19:24 UTC, a-chabin commented
Let's add a debounce decorator to optimize the network and fix the loader flashing

https://doka.guide/js/debounce/

2023-03-13 19:47 UTC, a-chabin commented on components/Loader/Loader.jsx
> +                <svg
Let's get loader from package:

1. `npm i ekb`
2. `import { ProjectsPanel, PROJECT_GUIDES, Theme } from 'ekb'`

2023-03-19 12:07 UTC, merged